# Generated by Django 4.0.4 on 2022-04-26 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, default=[], size=None),
        ),
    ]
